import os
import json
import argparse
import logging
from openai import OpenAI
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed
import time

def judge_one(idx, obj, client, args, system_prompt, max_retries=5):
    cur_idx = obj.get("idx", idx)
    instruction = obj.get("instruction", "").strip()
    input_text = obj.get("input", "").strip()
    ref_answer = obj.get("output", "").strip()
    model_answer = obj.get("llm_output", "").strip()

    if not ref_answer or not model_answer:
        logging.warning(f"Skipped idx={cur_idx}: output or llm_output is empty.")
        out = {
            "idx": cur_idx,
            "error": "No gold or predicted answer found."
        }
        return cur_idx, out

    user_prompt = (
        f"Instruction: {instruction}\n"
        f"Input: {input_text}\n"
        f"Reference Answer: {ref_answer}\n"
        f"Model Answer: {model_answer}\n"
    )

    wait_times = [5, 10, 15, 20, 25]
    last_exception = None
    for attempt in range(max_retries):
        try:
            completion = client.chat.completions.create(
                model=args.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                response_format={"type": "json_object"},
            )
            result = completion.choices[0].message.content
            logging.info(f"idx={cur_idx} success.")
            out = {
                "idx": cur_idx,
                "label_json": result,
                "instruction": instruction,
                "input": input_text,
                "reference_answer": ref_answer,
                "model_answer": model_answer,
                "retries": attempt + 1
            }
            return cur_idx, out
        except Exception as e:
            last_exception = e
            errmsg = f"idx={cur_idx}, attempt {attempt+1} error: {e}"
            print(errmsg)
            logging.error(errmsg)
            if attempt < max_retries - 1:
                time.sleep(wait_times[attempt])
    out = {
        "idx": cur_idx,
        "error": f"Failed after {max_retries} retries: {last_exception}",
        "instruction": instruction,
        "input": input_text,
        "reference_answer": ref_answer,
        "model_answer": model_answer,
        "retries": max_retries
    }
    return cur_idx, out

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default="qwen-max-latest", help="模型名称")
    parser.add_argument("--input", required=True, help="输入文件名（包含output和llm_output的json/jsonl）")
    parser.add_argument("--output", required=True, help="输出文件名")
    parser.add_argument("--log", default="pubmedqa_test.log", help="日志文件名")
    parser.add_argument("--api_key", default=os.getenv("DASHSCOPE_API_KEY"), help="API KEY")
    parser.add_argument("--base_url", default="https://dashscope.aliyuncs.com/compatible-mode/v1", help="API base url")
    parser.add_argument("--threads", type=int, default=4, help="并发线程数量")
    args = parser.parse_args()

    logging.basicConfig(
        filename=args.log,
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S"
    )
    client = OpenAI(api_key=args.api_key, base_url=args.base_url)

    # 读取数据文件（支持jsonl或json）
    with open(args.input, "r", encoding="utf-8") as f:
        first = f.read(1)
        f.seek(0)
        if first == "[":
            items = json.load(f)
        else:
            items = [json.loads(line) for line in f if line.strip()]

    system_prompt = (
        "You are an expert biomedical QA evaluator. For each sample, you'll receive:\n"
        "1. Instruction (the system prompt used for LLM generation)\n"
        "2. Input (the user prompt used for LLM generation)\n"
        "3. Reference Answer (gold standard)\n"
        "4. Model Answer (generated by the model under the given instruction and input)\n"
        "Your task: Judge whether the Model Answer is correct and complete with respect to the Reference Answer.\n"
        "Only output a JSON object with a field \"label\" whose value is \"True\" (if correct) or \"False\" (if incorrect).\n"
        "For example: { \"label\": \"True\" } or { \"label\": \"False\" }\n"
        "Here is an example:\n"
        "Instruction: Answer the question based on the following context: Programmed cell death (PCD) is the regulated death of cells within an organism. The lace plant (Aponogeton madagascariensis) produces perforations in its leaves through PCD. The leaves of the plant consist of a latticework of longitudinal and transverse veins enclosing areoles. PCD occurs in the cells at the center of these areoles and progresses outwards, stopping approximately five cells from the vasculature. The role of mitochondria during PCD has been recognized in animals; however, it has been less studied during PCD in plants. The following paper elucidates the role of mitochondrial dynamics during developmentally regulated PCD in vivo in A. madagascariensis. A single areole within a window stage leaf (PCD is occurring) was divided into three areas based on the progression of PCD; cells that will not undergo PCD (NPCD), cells in early stages of PCD (EPCD), and cells in late stages of PCD (LPCD). Window stage leaves were stained with the mitochondrial dye MitoTracker Red CMXRos and examined. Mitochondrial dynamics were delineated into four categories (M1-M4) based on characteristics including distribution, motility, and membrane potential (ΔΨm). A TUNEL assay showed fragmented nDNA in a gradient over these mitochondrial stages. Chloroplasts and transvacuolar strands were also examined using live cell imaging. The possible importance of mitochondrial permeability transition pore (PTP) formation during PCD was indirectly examined via in vivo cyclosporine A (CsA) treatment. This treatment resulted in lace plant leaves with a significantly lower number of perforations compared to controls, and that displayed mitochondrial dynamics similar to that of non-PCD cells.\n"
        "Input: Question: Do mitochondria play a role in remodelling lace plant leaves during programmed cell death?\n"
        "Reference Answer: Results depicted mitochondrial dynamics in vivo as PCD progresses within the lace plant, and highlight the correlation of this organelle with other organelles during developmental PCD. To the best of our knowledge, this is the first report of mitochondria and chloroplasts moving on transvacuolar strands to form a ring structure surrounding the nucleus during developmental PCD. Also, for the first time, we have shown the feasibility for the use of CsA in a whole plant system. Overall, our findings implicate the mitochondria as playing a critical and early role in developmentally regulated PCD in the lace plant.\n"
        "Model Answer: Mitochondria do play a role in the remodelling of lace plant leaves during programmed cell death (PCD). The study on Aponogeton madagascariensis, a lace plant, has shown that mitochondrial dynamics are intricately involved in the PCD process. Specifically, the research indicates that the role of mitochondria in PCD is multifaceted and includes changes in mitochondrial distribution, motility, and membrane potential (ΔΨm), which are categorized into four stages (M1-M4). These dynamics are closely associated with the progression of PCD, as evidenced by the TUNEL assay, which shows fragmented nuclear DNA (nDNA) in a gradient over these mitochondrial stages. Additionally, chloroplasts and transvacuolar strands are also examined, suggesting a broader cellular context for PCD. The possible importance of mitochondrial permeability transition pore (PTP) formation during PCD is indirectly examined via in vivo cyclosporine A (CsA) treatment, leading to a significant reduction in the number of perforations and displaying mitochondrial dynamics similar to non-PCD cells. This further supports the role of mitochondrial dynamics in the regulation of PCD and the subsequent remodelling of the leaf structure.\n"
        "Your output: { \"label\": \"True\" }"
    )

    idx2out = {}
    with ThreadPoolExecutor(max_workers=args.threads) as executor:
        futures = [
            executor.submit(judge_one, idx, obj, client, args, system_prompt)
            for idx, obj in enumerate(items)
        ]
        for future in tqdm(as_completed(futures), total=len(futures), desc="Evaluating QA"):
            cur_idx, out = future.result()
            idx2out[cur_idx] = out

    with open(args.output, "w", encoding="utf-8") as fout:
        for obj in items:
            cur_idx = obj.get("idx")
            out = idx2out.get(cur_idx, {"idx": cur_idx, "error": "No result generated."})
            fout.write(json.dumps(out, ensure_ascii=False) + "\n")
            fout.flush()
    logging.info(f"全部处理完成，结果保存在 {args.output}")

if __name__ == "__main__":
    main()